# fly.toml app configuration file generated for poiema-gallery-workerr on 2026-09-14T03:06:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poiema-gallery-workerr'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  LOG_LEVEL = 'info'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  ports = []
  processes = ['app']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
